baseURL: http://eskild.blog
languageCode:  en-us
title: eskild.blog

theme: PaperMod

# taxonomies:
#   tag: tags

menu:
  main:
    - name: Archive
      url: archives
      weight: 5
    - name: Tags
      url: tags
      weight: 10
    - name: RSS
      url: index.xml
      identifier: rss
      weight: 15
    - name: About
      url: about
      weight: 20

# changes to default settings
# canonifyurls: true

params:
    homeInfoParams:
        Title: Welcome!
        Content: Can be Info, links, about...

    socialIcons:
        - name: GitHub
          url: https://github.com/iameskild
        - name: LinkedIn
          url: https://linkedin.com/in/eskilderiksen/

  
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: ""

    defaultTheme: auto
    # disableThemeToggle: true
    # ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    # ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true