baseURL: https://www.eskild.blog
languageCode: en-us
title: eskild.blog

theme: PaperMod

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
  - name: Archive
    url: archives
    weight: 5
  - name: Projects
    url: projects
    weight: 10
  - name: Tags
    url: tags
    weight: 15
  - name: RSS
    url: index.xml
    identifier: rss
    weight: 20
  - name: About
    url: about
    weight: 25

params:
  homeInfoParams:
    Title: Welcome!

  socialIcons:
  - name: GitHub
    url: https://github.com/iameskild
  - name: LinkedIn
    url: https://linkedin.com/in/eskilderiksen/

  env: production
  description: ""

  defaultTheme: auto
  # disableThemeToggle: true
  # ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  # displayFullLangName: true
  ShowPostNavLinks: true
  # ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  # ShowRssButtonInSectionTermList: true
  # ShowToc: true
  ShowFullTextinRSS: true

  assets:
    favicon: "/favicon.ico"